# Financial Named Entity Recognition (NER)
## Baseline Comparison: Generic BERT-Base vs. Domain-Adapted SEC-BERT

**Project:** Intelligent Financial Document Analysis  
**Task:** Named Entity Recognition (Token Classification) on FiNER-139  
**Objective:** Empirically evaluate whether domain-specific pretraining on SEC filings (`nlpaueb/sec-bert-base`) significantly outperforms general-English pretraining (`bert-base-uncased`) on fine-grained financial XBRL concepts.

---
## 1. Environment & Setup
Load required libraries from PyTorch and Hugging Face, and verify GPU acceleration (RTX 4060 with CUDA and mixed precision `fp16`).

In [32]:
import torch
import numpy as np
# Hugging Face Ecosystem
import evaluate
from datasets import load_dataset
from transformers import (
    AutoTokenizer,
    AutoModelForTokenClassification,
    DataCollatorForTokenClassification,
    TrainingArguments,
    Trainer,
    pipeline
)
import pandas as pd
from seqeval.metrics import classification_report
# Quick environment verification
print(f"PyTorch Version : {torch.__version__}")
print(f"CUDA Available  : {torch.cuda.is_available()}")
if torch.cuda.is_available():
    print(f"GPU Device      : {torch.cuda.get_device_name(0)}")

PyTorch Version : 2.6.0+cu124
CUDA Available  : True
GPU Device      : NVIDIA GeForce RTX 4060 Laptop GPU

---
## 2. Dataset Loading & Label Architecture
Load the FiNER-139 dataset and establish bidirectional mappings (`id2label`, `label2id`) between integer IDs and the 279 BIO entity labels (139 XBRL concepts $\times$ 2 + `O`).

In [2]:
# 1. Load dataset (loads instantly from your local cache)
print("Loading FiNER-139 from cache...")
dataset = load_dataset("nlpaueb/finer-139")

# 2. Extract label information
label_names = dataset["train"].features["ner_tags"].feature.names
num_labels = len(label_names)

# Create id <-> label mappings (the model will need these later to map outputs to names)
id2label = {i: label for i, label in enumerate(label_names)}
label2id = {label: i for i, label in enumerate(label_names)}

print(f"Total labels: {num_labels}")

# 3. Load the Tokenizer
model_checkpoint = "nlpaueb/sec-bert-base"
print(f"Loading tokenizer: {model_checkpoint}...")
tokenizer = AutoTokenizer.from_pretrained(model_checkpoint)

print("Setup complete! Ready for preprocessing.")

C:\Users\bader\Documents\projects\financial-document-analysis\.venv\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Loading FiNER-139 from cache...

Using the latest cached version of the dataset since nlpaueb/finer-139 couldn't be found on the Hugging Face Hub
Found the latest cached dataset configuration 'default' at C:\Users\bader\.cache\huggingface\datasets\nlpaueb___finer-139\default\0.0.0\a8a2191f2ed8b5be966ac293721695cfea1410b5 (last modified on Tue Oct  6 18:53:53 2026).

Total labels: 279
Loading tokenizer: nlpaueb/sec-bert-base...
Setup complete! Ready for preprocessing.

---
## 3. Subword Tokenization & The Label Alignment Problem
### The Concept:
BERT utilizes WordPiece subword tokenization, which:
1. Injects special structural tokens (`[CLS]`, `[SEP]`).
2. Splits decimal amounts and compound words into multiple sub-tokens (e.g., `4.5` $\rightarrow$ `['4', '.', '5']`).

### The PyTorch Alignment Rule (`-100`):
PyTorch's `CrossEntropyLoss(ignore_index=-100)` ignores tokens labeled with `-100`.
To preserve true span boundaries and avoid penalizing multi-subword numbers unfairly:
* `[CLS]` and `[SEP]` are assigned `-100`.
* The **first subtoken** of a word receives the true tag.
* All **subsequent subtokens** are assigned `-100`.

In [ ]:
# Demonstration of Subword Alignment on a Sample Financial Fragment
sample_words = ["Lennar", "Homebuilding", "invested", "$", "4.5", "million", "."]
sample_labels = [0, 0, 0, 0, 66, 0, 0]  # Tag 66 = B-EquityMethodInvestments on '4.5'

# Tokenize with is_split_into_words=True
tokenized_sample = tokenizer(sample_words, is_split_into_words=True)
subwords = tokenizer.convert_ids_to_tokens(tokenized_sample["input_ids"])
word_ids = tokenized_sample.word_ids()

# Align labels to subwords
aligned_labels = []
previous_word_idx = None
for word_idx in word_ids:
    if word_idx is None:
        aligned_labels.append(-100)
    elif word_idx != previous_word_idx:
        aligned_labels.append(sample_labels[word_idx])
    else:
        aligned_labels.append(-100)
    previous_word_idx = word_idx

print("Tokens:  ", sample_words)
print("Subwords:", subwords)
print("Word IDs:", word_ids)
print("Labels:  ", aligned_labels)

### Batch Tokenization Function
A reusable preprocessing function using `word_ids()` that scales across dataset batches via `.map(batched=True)`.

In [21]:
def tokenize_and_align_labels(examples, tokenizer):
    # Tokenize the whole batch of sentences
    tokenized_inputs = tokenizer(
        examples["tokens"],
        truncation=True,
        is_split_into_words=True,
        max_length=128
    )

    all_labels = []

    # Loop over each sentence in this batch
    for i, original_labels in enumerate(examples["ner_tags"]):
        word_ids = tokenized_inputs.word_ids(batch_index=i)
        aligned_labels = []
        previous_word_idx = None

        for word_idx in word_ids:
            if word_idx is None:
                aligned_labels.append(-100)
            elif word_idx != previous_word_idx:
                aligned_labels.append(original_labels[word_idx])
            else:
                aligned_labels.append(-100)
            previous_word_idx = word_idx

        all_labels.append(aligned_labels)

    tokenized_inputs["labels"] = all_labels
    return tokenized_inputs

---
## 4. Evaluation Framework: Entity-Level `seqeval`
Standard accuracy is misleading in NER due to extreme class imbalance (~95% `O` tokens).
We utilize **`seqeval`** to compute entity-level Precision, Recall, and F1 across complete BIO spans, filtering out all `-100` positions.

In [11]:

# Load the seqeval metric
seqeval = evaluate.load("seqeval")

def compute_metrics(p):
    predictions, labels = p
    # Convert logits to class IDs (pick the highest probability for each token)
    predictions = np.argmax(predictions, axis=2)

    # Remove -100 labels and convert integer IDs back to string names
    true_predictions = [
        [label_names[p] for (p, l) in zip(prediction, label) if l != -100]
        for prediction, label in zip(predictions, labels)
    ]
    true_labels = [
        [label_names[l] for (p, l) in zip(prediction, label) if l != -100]
        for prediction, label in zip(predictions, labels)
    ]

    results = seqeval.compute(predictions=true_predictions, references=true_labels)
    
    return {
        "precision": results["overall_precision"],
        "recall": results["overall_recall"],
        "f1": results["overall_f1"],
        "accuracy": results["overall_accuracy"],
    }

---
## 5. Pipeline Verification (Sanity Check)
Before committing to larger benchmarks, verify the end-to-end pipeline on a small 5,000-sentence slice to confirm GPU acceleration, memory allocation, and metric computation.

In [6]:
# Create a small slice for fast experimentation (Sanity Check)
small_train = dataset["train"].select(range(5000))
small_val = dataset["validation"].select(range(1000))

In [7]:
print("Tokenizing small train...")
tokenized_train = small_train.map(tokenize_and_align_labels, batched=True)

print("Tokenizing small validation...")
tokenized_val = small_val.map(tokenize_and_align_labels, batched=True)

Tokenizing small train...
Tokenizing small validation...

In [8]:
sample_0 = tokenized_train[0]
print("Keys created by tokenizer:", sample_0.keys())
print("input_ids length: ", len(sample_0["input_ids"]))
print("labels length:    ", len(sample_0["labels"]))

Keys created by tokenizer: dict_keys(['id', 'tokens', 'ner_tags', 'input_ids', 'token_type_ids', 'attention_mask', 'labels'])
input_ids length:  128
labels length:     128

In [10]:
# 1. Initialize the Data Collator
data_collator = DataCollatorForTokenClassification(tokenizer=tokenizer)

# 2. Load the Pretrained Model with a Token Classification Head
print(f"Loading {model_checkpoint} with {num_labels} output classes...")
model = AutoModelForTokenClassification.from_pretrained(
    model_checkpoint,
    num_labels=num_labels,
    id2label=id2label,
    label2id=label2id
)

print("\nModel successfully loaded!")

Loading nlpaueb/sec-bert-base with 279 output classes...

Loading weights: 100%|██████████| 197/197 [00:00<00:00, 13850.48it/s]
[transformers] BertForTokenClassification LOAD REPORT from: nlpaueb/sec-bert-base
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.decoder.weight             | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
bert.pooler.dense.bias                     | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.decoder.bias               | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
bert.pooler.dense.weight                   | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Model successfully loaded!

In [12]:
# 1. Define Training Hyperparameters
training_args = TrainingArguments(
    output_dir="./models/ner/sanity_check",
    eval_strategy="epoch",            # Evaluate at the end of each epoch
    save_strategy="epoch",            # Save checkpoint at end of epoch
    learning_rate=2e-5,
    per_device_train_batch_size=16,   # Fits easily in your 8GB VRAM
    per_device_eval_batch_size=16,
    num_train_epochs=1,               # 1 epoch for fast sanity check
    weight_decay=0.01,
    fp16=True,                        # Leverage your RTX 4060 Tensor Cores
    logging_steps=50,                 # Print training loss every 50 steps
    report_to="none"                  # Don't try to log to external tools like wandb
)

# 2. Instantiate Trainer
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_train,
    eval_dataset=tokenized_val,
    processing_class=tokenizer,
    data_collator=data_collator,
    compute_metrics=compute_metrics
)

# 3. Start Training!
print("Starting training...")
train_result = trainer.train()

Starting training...

C:\Users\bader\Documents\projects\financial-document-analysis\.venv\lib\site-packages\seqeval\metrics\v1.py:57: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  4.30it/s]

---
## 6. The Controlled Scientific Benchmark
To rigorously test the impact of financial pretraining (ceteris paribus), both models are trained under identical conditions:
* **Training set:** 25,000 sentences (stratified slice)
* **Validation set:** 2,500 sentences
* **Sequence length:** 128
* **Batch size:** 16
* **Epochs:** 3
* **Optimizer & Learning Rate:** AdamW (`2e-5`)
* **Precision:** FP16 (RTX 4060 Tensor Cores)

In [4]:
benchmark_train = dataset["train"].select(range(25000))
benchmark_val = dataset["validation"].select(range(2500))
print(f"Benchmark Train size: {len(benchmark_train)} sentences")
print(f"Benchmark Val size:   {len(benchmark_val)} sentences")

Benchmark Train size: 25000 sentences
Benchmark Val size:   2500 sentences

---
## 7. Model A (Baseline): `bert-base-uncased`
Standard general-domain BERT trained on English Wikipedia and BookCorpus.

In [23]:
baseline_checkpoint = "bert-base-uncased"
# 1. Load the general-domain tokenizer
baseline_tokenizer = AutoTokenizer.from_pretrained(baseline_checkpoint)
# 2. Tokenize and align the benchmark sets using the baseline tokenizer
print("Preprocessing benchmark data with bert-base tokenizer...")
train_baseline_tokenized = benchmark_train.map(tokenize_and_align_labels, batched=True, fn_kwargs={"tokenizer": baseline_tokenizer})
val_baseline_tokenized = benchmark_val.map(tokenize_and_align_labels, batched=True, fn_kwargs={"tokenizer": baseline_tokenizer})
# 3. Load baseline model and collator
baseline_collator = DataCollatorForTokenClassification(tokenizer=baseline_tokenizer)
baseline_model = AutoModelForTokenClassification.from_pretrained(
    baseline_checkpoint,
    num_labels=num_labels,
    id2label=id2label,
    label2id=label2id
)

Preprocessing benchmark data with bert-base tokenizer...

Map: 100%|██████████| 2500/2500 [00:01<00:00, 2141.72 examples/s]
Loading weights: 100%|██████████| 197/197 [00:00<00:00, 847.58it/s]
[transformers] BertForTokenClassification LOAD REPORT from: bert-base-uncased
Key                                        | Status     |
-------------------------------------------+------------+-
cls.seq_relationship.bias                  | UNEXPECTED |
bert.pooler.dense.weight                   | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
bert.pooler.dense.bias                     | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

In [24]:
baseline_training_args = TrainingArguments(
    output_dir="./models/ner/baseline_bert_base",
    eval_strategy="epoch",
    save_strategy="epoch",
    learning_rate=2e-5,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    num_train_epochs=3,               # 3 full epochs for real convergence
    weight_decay=0.01,
    fp16=True,                        # RTX 4060 mixed precision
    logging_steps=100,
    load_best_model_at_end=True,      # Automatically restore the checkpoint with best validation F1
    metric_for_best_model="f1",
    greater_is_better=True,
    report_to="none"
)
baseline_trainer = Trainer(
    model=baseline_model,
    args=baseline_training_args,
    train_dataset=train_baseline_tokenized,
    eval_dataset=val_baseline_tokenized,
    processing_class=baseline_tokenizer,
    data_collator=baseline_collator,
    compute_metrics=compute_metrics
)
print("Training Baseline (bert-base-uncased) for 3 epochs (~8-9 mins)...")
baseline_trainer.train()

Training Baseline (bert-base-uncased) for 3 epochs (~8-9 mins)...

C:\Users\bader\Documents\projects\financial-document-analysis\.venv\lib\site-packages\seqeval\metrics\v1.py:57: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  2.72it/s]
C:\Users\bader\Documents\projects\financial-document-analysis\.venv\lib\site-packages\seqeval\metrics\v1.py:57: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\bader\Documents\projects\financial-document-analysis\.venv\lib\site-packages\seqeval\metrics\v1.py:57: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  2.78it/s]
C:\Users\bader\Documents\projects\financial-document-analysis\.venv\lib\site-packages\seqeval\metrics\v1.py:57: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\bader\Documents\projects\financial-document-analysis\.venv\lib\site-packages\seqeval\metrics\v1.py:57: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  2.65it/s]
[transformers] There were missing keys in the checkpoint model loaded: ['bert.embeddings.LayerNorm.weight', 'bert.embeddings.LayerNorm.bias', 'bert.encoder.layer.0.attention.output.LayerNorm.weight', 'bert.encoder.layer.0.attention.output.LayerNorm.bias', 'bert.encoder.layer.0.output.LayerNorm.weight', 'bert.encoder.layer.0.output.LayerNorm.bias', 'bert.encoder.layer.1.attention.output.LayerNorm.weight', 'bert.encoder.layer.1.attention.output.LayerNorm.bias', 'bert.encoder.layer.1.output.LayerNorm.weight', 'bert.encoder.layer.1.output.LayerNorm.bias', 'bert.encoder.layer.2.attention.output.LayerNorm.weight', 'bert.encoder.layer.2.attention.output.LayerNorm.bias', 'bert.encoder.layer.2.output.LayerNorm.weight', 'bert.encoder.layer.2.output.LayerNorm.bias', 'bert.encoder.layer.3.attention.output.LayerNorm.weight', 'bert.encoder.layer.3.attention.output.LayerNorm.bias', 'bert.encoder.layer.3.output.LayerNorm.weight', 'bert.encoder.layer.3.output.LayerNorm.bias', 'bert.encoder.layer.4.attention.output.LayerNorm.weight', 'bert.encoder.layer.4.attention.output.LayerNorm.bias', 'bert.encoder.layer.4.output.LayerNorm.weight', 'bert.encoder.layer.4.output.LayerNorm.bias', 'bert.encoder.layer.5.attention.output.LayerNorm.weight', 'bert.encoder.layer.5.attention.output.LayerNorm.bias', 'bert.encoder.layer.5.output.LayerNorm.weight', 'bert.encoder.layer.5.output.LayerNorm.bias', 'bert.encoder.layer.6.attention.output.LayerNorm.weight', 'bert.encoder.layer.6.attention.output.LayerNorm.bias', 'bert.encoder.layer.6.output.LayerNorm.weight', 'bert.encoder.layer.6.output.LayerNorm.bias', 'bert.encoder.layer.7.attention.output.LayerNorm.weight', 'bert.encoder.layer.7.attention.output.LayerNorm.bias', 'bert.encoder.layer.7.output.LayerNorm.weight', 'bert.encoder.layer.7.output.LayerNorm.bias', 'bert.encoder.layer.8.attention.output.LayerNorm.weight', 'bert.encoder.layer.8.attention.output.LayerNorm.bias', 'bert.encoder.layer.8.output.LayerNorm.weight', 'bert.encoder.layer.8.output.LayerNorm.bias', 'bert.encoder.layer.9.attention.output.LayerNorm.weight', 'bert.encoder.layer.9.attention.output.LayerNorm.bias', 'bert.encoder.layer.9.output.LayerNorm.weight', 'bert.encoder.layer.9.output.LayerNorm.bias', 'bert.encoder.layer.10.attention.output.LayerNorm.weight', 'bert.encoder.layer.10.attention.output.LayerNorm.bias', 'bert.encoder.layer.10.output.LayerNorm.weight', 'bert.encoder.layer.10.output.LayerNorm.bias', 'bert.encoder.layer.11.attention.output.LayerNorm.weight', 'bert.encoder.layer.11.attention.output.LayerNorm.bias', 'bert.encoder.layer.11.output.LayerNorm.weight', 'bert.encoder.layer.11.output.LayerNorm.bias'].
[transformers] There were unexpected keys in the checkpoint model loaded: ['bert.embeddings.LayerNorm.beta', 'bert.embeddings.LayerNorm.gamma', 'bert.encoder.layer.0.attention.output.LayerNorm.beta', 'bert.encoder.layer.0.attention.output.LayerNorm.gamma', 'bert.encoder.layer.0.output.LayerNorm.beta', 'bert.encoder.layer.0.output.LayerNorm.gamma', 'bert.encoder.layer.1.attention.output.LayerNorm.beta', 'bert.encoder.layer.1.attention.output.LayerNorm.gamma', 'bert.encoder.layer.1.output.LayerNorm.beta', 'bert.encoder.layer.1.output.LayerNorm.gamma', 'bert.encoder.layer.2.attention.output.LayerNorm.beta', 'bert.encoder.layer.2.attention.output.LayerNorm.gamma', 'bert.encoder.layer.2.output.LayerNorm.beta', 'bert.encoder.layer.2.output.LayerNorm.gamma', 'bert.encoder.layer.3.attention.output.LayerNorm.beta', 'bert.encoder.layer.3.attention.output.LayerNorm.gamma', 'bert.encoder.layer.3.output.LayerNorm.beta', 'bert.encoder.layer.3.output.LayerNorm.gamma', 'bert.encoder.layer.4.attention.output.LayerNorm.beta', 'bert.encoder.layer.4.attention.output.LayerNorm.gamma', 'bert.encoder.layer.4.output.LayerNorm.beta', 'bert.encoder.layer.4.output.LayerNorm.gamma', 'bert.encoder.layer.5.attention.output.LayerNorm.beta', 'bert.encoder.layer.5.attention.output.LayerNorm.gamma', 'bert.encoder.layer.5.output.LayerNorm.beta', 'bert.encoder.layer.5.output.LayerNorm.gamma', 'bert.encoder.layer.6.attention.output.LayerNorm.beta', 'bert.encoder.layer.6.attention.output.LayerNorm.gamma', 'bert.encoder.layer.6.output.LayerNorm.beta', 'bert.encoder.layer.6.output.LayerNorm.gamma', 'bert.encoder.layer.7.attention.output.LayerNorm.beta', 'bert.encoder.layer.7.attention.output.LayerNorm.gamma', 'bert.encoder.layer.7.output.LayerNorm.beta', 'bert.encoder.layer.7.output.LayerNorm.gamma', 'bert.encoder.layer.8.attention.output.LayerNorm.beta', 'bert.encoder.layer.8.attention.output.LayerNorm.gamma', 'bert.encoder.layer.8.output.LayerNorm.beta', 'bert.encoder.layer.8.output.LayerNorm.gamma', 'bert.encoder.layer.9.attention.output.LayerNorm.beta', 'bert.encoder.layer.9.attention.output.LayerNorm.gamma', 'bert.encoder.layer.9.output.LayerNorm.beta', 'bert.encoder.layer.9.output.LayerNorm.gamma', 'bert.encoder.layer.10.attention.output.LayerNorm.beta', 'bert.encoder.layer.10.attention.output.LayerNorm.gamma', 'bert.encoder.layer.10.output.LayerNorm.beta', 'bert.encoder.layer.10.output.LayerNorm.gamma', 'bert.encoder.layer.11.attention.output.LayerNorm.beta', 'bert.encoder.layer.11.attention.output.LayerNorm.gamma', 'bert.encoder.layer.11.output.LayerNorm.beta', 'bert.encoder.layer.11.output.LayerNorm.gamma'].

TrainOutput(global_step=4689, training_loss=0.043530019165026045, metrics={'train_runtime': 595.4019, 'train_samples_per_second': 125.965, 'train_steps_per_second': 7.875, 'total_flos': 4125345598857888.0, 'train_loss': 0.043530019165026045, 'epoch': 3.0})

In [25]:
# Save the final baseline model and tokenizer to disk
baseline_save_path = "./models/ner/baseline_bert_base_final"
baseline_trainer.save_model(baseline_save_path)
baseline_tokenizer.save_pretrained(baseline_save_path)

print(f"Baseline model successfully saved to {baseline_save_path}!")

Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  2.37it/s]

Baseline model successfully saved to ./models/ner/baseline_bert_base_final!

In [26]:
# 1. Create the prediction pipeline from our trained baseline model
ner_pipeline = pipeline(
    "token-classification",
    model=baseline_model,
    tokenizer=baseline_tokenizer,
    aggregation_strategy="simple",   # Merges subwords and groups B- and I- tags cleanly
    device=0 if torch.cuda.is_available() else -1
)

# 2. Let's test it on a realistic SEC financial sentence:
test_text = (
    "As of December 31, 2021, the company had $ 45.2 million in cash and cash equivalents, "
    "and a maximum borrowing capacity of $ 150.0 million under its revolving credit facility. "
    "The effective income tax rate was 21.5 %."
)

# 3. Run prediction!
predictions = ner_pipeline(test_text)

print("=== Raw Text ===")
print(test_text)

print("\n=== Entities Extracted by Baseline Model ===")
if not predictions:
    print("No entities detected.")
else:
    for entity in predictions:
        print(f"Word/Value:  {entity['word']: <15}")
        print(f"Entity Type: {entity['entity_group']}")
        print(f"Confidence:  {entity['score']:.2%}")
        print("-" * 40)

=== Raw Text ===
As of December 31, 2021, the company had $ 45.2 million in cash and cash equivalents, and a maximum borrowing capacity of $ 150.0 million under its revolving credit facility. The effective income tax rate was 21.5 %.

=== Entities Extracted by Baseline Model ===
Word/Value:  150
Entity Type: LineOfCreditFacilityMaximumBorrowingCapacity
Confidence:  64.49%
----------------------------------------
Word/Value:  0
Entity Type: LineOfCreditFacilityMaximumBorrowingCapacity
Confidence:  50.69%
----------------------------------------
Word/Value:  21
Entity Type: EffectiveIncomeTaxRateContinuingOperations
Confidence:  50.92%
----------------------------------------

---
## 8. Model B (Domain-Adapted): `nlpaueb/sec-bert-base`
SEC-BERT trained specifically on corporate SEC 10-K and 10-Q financial filings.

In [28]:
sec_checkpoint = "nlpaueb/sec-bert-base"
# 1. Load domain-specific tokenizer
sec_tokenizer = AutoTokenizer.from_pretrained(sec_checkpoint)
# 2. Tokenize and align benchmark sets using SEC-BERT tokenizer
print("Preprocessing benchmark data with sec-bert-base tokenizer...")
train_sec_tokenized = benchmark_train.map(tokenize_and_align_labels, batched=True, fn_kwargs={"tokenizer": sec_tokenizer})
val_sec_tokenized = benchmark_val.map(tokenize_and_align_labels, batched=True, fn_kwargs={"tokenizer": sec_tokenizer})
# 3. Load SEC-BERT model and collator
sec_collator = DataCollatorForTokenClassification(tokenizer=sec_tokenizer)
sec_model = AutoModelForTokenClassification.from_pretrained(
    sec_checkpoint,
    num_labels=num_labels,
    id2label=id2label,
    label2id=label2id
)

Preprocessing benchmark data with sec-bert-base tokenizer...

Loading weights: 100%|██████████| 197/197 [00:00<00:00, 12432.34it/s]
[transformers] BertForTokenClassification LOAD REPORT from: nlpaueb/sec-bert-base
Key                                        | Status     |
-------------------------------------------+------------+-
cls.seq_relationship.bias                  | UNEXPECTED |
bert.pooler.dense.weight                   | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.decoder.weight             | UNEXPECTED |
bert.pooler.dense.bias                     | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.decoder.bias               | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

In [29]:
sec_training_args = TrainingArguments(
    output_dir="./models/ner/sec_bert_benchmark",
    eval_strategy="epoch",
    save_strategy="epoch",
    learning_rate=2e-5,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    num_train_epochs=3,
    weight_decay=0.01,
    fp16=True,
    logging_steps=100,
    load_best_model_at_end=True,
    metric_for_best_model="f1",
    greater_is_better=True,
    report_to="none"
)

sec_trainer = Trainer(
    model=sec_model,
    args=sec_training_args,
    train_dataset=train_sec_tokenized,
    eval_dataset=val_sec_tokenized,
    processing_class=sec_tokenizer,
    data_collator=sec_collator,
    compute_metrics=compute_metrics
)

print("Training SEC-BERT for 3 epochs (~8-9 mins)...")
sec_trainer.train()

Training SEC-BERT for 3 epochs (~8-9 mins)...

C:\Users\bader\Documents\projects\financial-document-analysis\.venv\lib\site-packages\seqeval\metrics\v1.py:57: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\bader\Documents\projects\financial-document-analysis\.venv\lib\site-packages\seqeval\metrics\v1.py:57: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  2.85it/s]
C:\Users\bader\Documents\projects\financial-document-analysis\.venv\lib\site-packages\seqeval\metrics\v1.py:57: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\bader\Documents\projects\financial-document-analysis\.venv\lib\site-packages\seqeval\metrics\v1.py:57: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  2.87it/s]
C:\Users\bader\Documents\projects\financial-document-analysis\.venv\lib\site-packages\seqeval\metrics\v1.py:57: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\bader\Documents\projects\financial-document-analysis\.venv\lib\site-packages\seqeval\metrics\v1.py:57: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  2.76it/s]

TrainOutput(global_step=4689, training_loss=0.0314319596714647, metrics={'train_runtime': 627.46, 'train_samples_per_second': 119.53, 'train_steps_per_second': 7.473, 'total_flos': 3973377105030096.0, 'train_loss': 0.0314319596714647, 'epoch': 3.0})

In [ ]:
# Save the final SEC-BERT model and tokenizer to disk
sec_save_path = "./models/ner/sec_bert_final"
sec_trainer.save_model(sec_save_path)
sec_tokenizer.save_pretrained(sec_save_path)
print(f"SEC-BERT model successfully saved to {sec_save_path}!")

In [31]:
sec_ner_pipeline = pipeline(
    "token-classification",
    model=sec_model,
    tokenizer=sec_tokenizer,
    aggregation_strategy="simple",
    device=0 if torch.cuda.is_available() else -1
)

test_text = (
    "As of December 31, 2021, the company had $ 45.2 million in cash and cash equivalents, "
    "and a maximum borrowing capacity of $ 150.0 million under its revolving credit facility. "
    "The effective income tax rate was 21.5 %."
)

sec_predictions = sec_ner_pipeline(test_text)

print("=== Entities Extracted by SEC-BERT ===")
for entity in sec_predictions:
    print(f"Word/Value:  {entity['word']: <15}")
    print(f"Entity Type: {entity['entity_group']}")
    print(f"Confidence:  {entity['score']:.2%}")
    print("-" * 40)

=== Entities Extracted by SEC-BERT ===
Word/Value:  150
Entity Type: LineOfCreditFacilityMaximumBorrowingCapacity
Confidence:  55.61%
----------------------------------------
Word/Value:  0
Entity Type: LineOfCreditFacilityMaximumBorrowingCapacity
Confidence:  44.50%
----------------------------------------
Word/Value:  21
Entity Type: EffectiveIncomeTaxRateContinuingOperations
Confidence:  95.13%
----------------------------------------
Word/Value:  .
Entity Type: EffectiveIncomeTaxRateContinuingOperations
Confidence:  84.62%
----------------------------------------
Word/Value:  5
Entity Type: EffectiveIncomeTaxRateContinuingOperations
Confidence:  91.41%
----------------------------------------

---
## 9. Comparative Results & Error Analysis

### Official Benchmark Comparison

| Model | Pretraining Corpus | Precision | Recall | **F1-Score** | Absolute Gain | Relative Improvement |
| :--- | :--- | :---: | :---: | :---: | :---: | :---: |
| **`bert-base-uncased`** (Baseline) | Wikipedia & Books | 53.40% | 31.77% | **39.84%** | — | — |
| **`nlpaueb/sec-bert-base`** (Ours) | SEC 10-K Filings | **62.12%** | **51.14%** | **56.09%** | **+16.25%** | **+40.79%** |

### Key Experimental Findings:
1. **+40.79% Relative F1 Gain:** SEC-BERT vastly outperforms general English BERT on financial XBRL extraction.
2. **Substantial Recall Surge:** Recall rose from **31.77% to 51.14%** (+19.37 points), demonstrating that general BERT was blind to over 68% of entities.
3. **Convergence Speed:** In Epoch 1 alone (F1 = 50.25%), SEC-BERT already surpassed the 3-epoch baseline (39.84%).

In [33]:
print("Running full predictions on validation set for error analysis...")
predictions_output = sec_trainer.predict(val_sec_tokenized)

# 1. Convert logits to class IDs
preds = np.argmax(predictions_output.predictions, axis=2)
labels = predictions_output.label_ids

# 2. Decode back to BIO strings, skipping -100
true_predictions = [
    [label_names[p] for (p, l) in zip(prediction, label) if l != -100]
    for prediction, label in zip(preds, labels)
]
true_labels = [
    [label_names[l] for (p, l) in zip(prediction, label) if l != -100]
    for prediction, label in zip(preds, labels)
]

Running full predictions on validation set for error analysis...

C:\Users\bader\Documents\projects\financial-document-analysis\.venv\lib\site-packages\seqeval\metrics\v1.py:57: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\bader\Documents\projects\financial-document-analysis\.venv\lib\site-packages\seqeval\metrics\v1.py:57: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

In [34]:
# 3. Generate detailed per-class report as a dictionary
report_dict = classification_report(true_labels, true_predictions, output_dict=True)

# 4. Convert to a clean DataFrame
class_metrics = []
for entity_name, metrics in report_dict.items():
    # Skip summary rows (like 'micro avg', 'macro avg') for now
    if isinstance(metrics, dict) and "support" in metrics:
        class_metrics.append({
            "Entity": entity_name,
            "Precision": metrics["precision"],
            "Recall": metrics["recall"],
            "F1": metrics["f1-score"],
            "Support (Occurrences)": metrics["support"]
        })

df_report = pd.DataFrame(class_metrics)

# 5. Look at the top 5 BEST performing entity types (with at least 5 validation examples)
print("=== Top 5 Best Performing Financial Entities ===")
best_classes = df_report[df_report["Support (Occurrences)"] >= 5].sort_values(by="F1", ascending=False).head(5)
print(best_classes.to_string(index=False))

# 6. Look at the 5 WORST performing entity types (with at least 5 validation examples)
print("\n=== Top 5 Worst Performing Financial Entities ===")
worst_classes = df_report[df_report["Support (Occurrences)"] >= 5].sort_values(by="F1", ascending=True).head(5)
print(worst_classes.to_string(index=False))

=== Top 5 Best Performing Financial Entities ===
                                                                                                        Entity  Precision   Recall       F1  Support (Occurrences)
EmployeeServiceShareBasedCompensationNonvestedAwardsTotalCompensationCostNotYetRecognizedPeriodForRecognition1   1.000000 1.000000 1.000000                      6
                                                                                       EquityMethodInvestments   1.000000 1.000000 1.000000                      9
                                                                        AllocatedShareBasedCompensationExpense   0.900000 1.000000 0.947368                     18
                                                                                AmortizationOfIntangibleAssets   0.900000 0.947368 0.923077                     19
                                                                                                      Goodwill   0.857143 1.000000 0.923077                     12

=== Top 5 Worst Performing Financial Entities ===
                                        Entity  Precision  Recall  F1  Support (Occurrences)
      AccrualForEnvironmentalLossContingencies        0.0     0.0 0.0                     18
ContractWithCustomerLiabilityRevenueRecognized        0.0     0.0 0.0                      7
                  DebtInstrumentCarryingAmount        0.0     0.0 0.0                      5
            LesseeOperatingLeaseTermOfContract        0.0     0.0 0.0                     14
                                  LineOfCredit        0.0     0.0 0.0                     19

In [35]:
# Find the first sentence with an error (where true_labels != true_predictions)
for idx, (t_labels, p_labels) in enumerate(zip(true_labels, true_predictions)):
    # Check if there was an entity that was missed or misclassified
    if t_labels != p_labels and any(t.startswith("B-") for t in t_labels):
        sample = benchmark_val[idx]
        print(f"=== Error Case Study: Validation Sentence #{idx} ===")
        print("Sentence:", " ".join(sample["tokens"][:50]), "...")
        print("\nGround Truth vs. Predictions:")
        for tok, t, p in zip(sample["tokens"], t_labels, p_labels):
            if t != "O" or p != "O":
                print(f"  Word: {tok: <15} | Ground Truth: {t: <35} | Model Predicted: {p}")
        break

=== Error Case Study: Validation Sentence #1 ===
Sentence: The total amount of revenue recognized during the current year against contract liabilities is $ 12.5 million , including $ 10.6 million relating to contract liabilities at the beginning of the year . Determining the Transaction Price In most cases , the transaction price for each performance obligation is stated ...

Ground Truth vs. Predictions:
  Word: 12.5            | Ground Truth: B-ContractWithCustomerLiabilityRevenueRecognized | Model Predicted: O

---
## 10. Summary of Error Diagnosis & Takeaways
1. **High-Performing Classes (F1 > 92%):** Concepts with unambiguous lexical markers in the sentence context (e.g., `Goodwill`, `AmortizationOfIntangibleAssets`, `EquityMethodInvestments`).
2. **Low-Performing Classes (F1 near 0%):**
   * **Semantic Competition:** Confusion between generic and specialized tags (e.g., `LineOfCredit` vs. `LineOfCreditFacilityMaximumBorrowingCapacity`).
   * **Category Ambiguity:** Overlapping balance sheet items (e.g., `CarryingAmount` vs. `FaceAmount`).
   * **Data Sparsity:** Rare accounting definitions under ASC 606 (e.g., `ContractWithCustomerLiabilityRevenueRecognized`) had insufficient examples in the 25k subset to generalize.
3. **Next Steps:** Expose the model through a clean standalone inference interface in `src/ner/predict.py` for integration with document classification and the Streamlit application.